### ISSUE TITLE
Playbook broken due to missing python-gnupg dependency

### ISSUE THREAD

**Issue by NEXUS2345** [BrashEndeavours/hotwax#11]
It appears that python-gnupg has been removed from repos due to Python 2.7 reaching end of support. This means the playbook fails to install.

TASK [Install Samba compilation prerequisites] *********************************
fatal: [127.0.0.1]: FAILED! => changed=false 
  msg: No package matching 'python-gnupg' is available

**Comment by pranaylikhitkar** [comment]
Try temporarily adding Debian repo to sources list. And then try again ? https://www.kali.org/tutorials/advanced-package-management-in-kali-linux/

**Comment by NEXUS2345** [comment]
@pranaylikhitkar the issue is already resolved by #9 so really all it needs is a pull request review and merge to fix.

**Comment by BrashEndeavours** [comment]
Re
